name: CI Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    name: cargo-test-and-clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check Formatting
        run: cargo fmt --check
        
      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Run Tests
        run: cargo test
